"""initial schema

Revision ID: 75cbff39fa59
Revises: 
Create Date: 2026-07-26 13:35:36.019878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cbff39fa59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('register_type', sa.Enum('CLIENT', 'PLATFORM', name='registertype'), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('column_map', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('pay_period_year', sa.Integer(), nullable=False),
    sa.Column('pay_period_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('external_employee_id', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=10), nullable=True),
    sa.Column('is_permanent_resident', sa.Boolean(), nullable=False),
    sa.Column('elected_before_1998_08_01', sa.Boolean(), nullable=False),
    sa.Column('date_of_joining', sa.String(length=10), nullable=True),
    sa.Column('date_of_exit', sa.String(length=10), nullable=True),
    sa.Column('unpaid_leave_days', sa.Integer(), nullable=False),
    sa.Column('work_state', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('is_director_fee_only', sa.Boolean(), nullable=False),
    sa.Column('data_quality_flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'external_employee_id', name='uq_employee_project_extid')
    )
    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('register_type', sa.Enum('CLIENT', 'PLATFORM', name='registertype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mapping_template_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mapping_template_id'], ['mapping_templates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_component_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_execution_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expected_employee_amount', sa.Float(), nullable=True),
    sa.Column('expected_employer_amount', sa.Float(), nullable=True),
    sa.Column('expected_total_amount', sa.Float(), nullable=True),
    sa.Column('explanation', sa.String(length=1000), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('client_value', sa.Float(), nullable=True),
    sa.Column('platform_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('classification', sa.Enum('NOT_CALCULATED_ONE_SIDE', 'AMOUNT_MISMATCH_WITHIN_TOLERANCE', 'AMOUNT_MISMATCH_BEYOND_TOLERANCE', 'RATE_SLAB_MISMATCH', 'ELIGIBILITY_MISMATCH', 'DATA_QUALITY_ISSUE', 'NO_VARIANCE', name='varianceclassification'), nullable=False),
    sa.Column('suggestion_outcome', sa.Enum('PLATFORM_CORRECT', 'CLIENT_CORRECT', 'INCONCLUSIVE', 'NOT_APPLICABLE', name='suggestionoutcome'), nullable=False),
    sa.Column('recommended_action', sa.String(length=1000), nullable=False),
    sa.Column('explanation', sa.String(length=2000), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ai_explanation', sa.String(length=4000), nullable=True),
    sa.Column('resolution_status', sa.Enum('OPEN', 'PENDING_CLIENT', 'PENDING_INTERNAL', 'RESOLVED', name='resolutionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variance_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CONFIRMED', 'REJECTED', 'NEEDS_CORRECTION', name='feedbackaction'), nullable=False),
    sa.Column('consultant', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variance_id'], ['variances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('variances')
    op.drop_table('rule_execution_results')
    op.drop_table('pay_component_values')
    op.drop_table('registers')
    op.drop_table('employees')
    op.drop_table('audit_log')
    op.drop_table('projects')
    op.drop_table('organizations')
    op.drop_table('mapping_templates')
    # ### end Alembic commands ###
